{{- range .items}}
  {{- $schedulable := true }}
  {{- range .spec.taints}}
    {{- if eq .effect "NoSchedule"}}
      {{- $schedulable := false }}
    {{- end}}
  {{- end}}
  {{- if $schedulable }}
kind: Job
apiVersion: batch/v1
metadata:
  namespace: {{namespace}}
  name: copy-certs-{{.metadata.uid}}
spec:
  template:
    metadata:
      name: copy-certs-{{.metadata.uid}}
    spec:
      serviceAccountName: trow
      restartPolicy: OnFailure
      containers:
        - name: copy-certs-{{.metadata.uid}}
          image: containersol/trow:copy-certs
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/docker
              name: cert-dir
            - mountPath: /hostfile
              name: host-dir
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
#          securityContext:
#            privileged: true
      volumes:
        - name: cert-dir
          hostPath: 
            path: /etc/docker
        - name: host-dir
          hostPath: 
            path: /etc/hosts
      nodeSelector: 
        kubernetes.io/hostname: '{{index .metadata.labels "kubernetes.io/hostname"}}'
---
{{- end}}{{- end}}
